esphome:
  name: feather-huzzah32-heartbeat

esp32:
  board: featheresp32
  framework:
    type: arduino

logger:

switch:
  - platform: gpio
    id: onboard_led
    internal: true
    pin: GPIO13
    restore_mode: ALWAYS_OFF

script:
  - id: heartbeat
    mode: single
    then:
      - switch.turn_on: onboard_led
      - delay: 80ms
      - switch.turn_off: onboard_led
      - delay: 120ms
      - switch.turn_on: onboard_led
      - delay: 80ms
      - switch.turn_off: onboard_led
      - delay: 720ms

interval:
  - interval: 1s
    then:
      - script.execute: heartbeat
